### ISSUE TITLE
Feature request: Extract method

### ISSUE THREAD

**Issue by devantler** [sharklasers996/csharp-helper#1]
Would it be possible for you to provide an extract method refactoring option, so running the command with the some statements highlighted, would create a new method with the statements inside. Preferably the new method would have the correct parameters and return value to match what has been extracted.

**Comment by sharklasers996** [comment]
I'm not sure how extracted statements would be mapped to parameters/return value, could you provide code example before command has been called and after?

**Comment by devantler** [comment]
Sprry i never answered, forgot all about it 🤯 This is possible with Roslyn now, so i will close this issue :-)
